POST http://localhost:3001/api/gifts
Content-Type: application/json

{
  "name": "lailalahja",
  "content": "mitä vaan",
  "url": ["www.autoa.fi", "www.ksksksks.com"],
  "userId": "5fca1e0287566843a666d41b"
}